services:
  app:
    container_name: nexora
    #image: m4rkus28/nexora:latest
    build:
      context: .
      dockerfile: Dockerfile
    # Define variable
    environment:
      - WORKERS=1
    volumes:
      - ./dev-poet-461212-d9-35a36f7ab681.json:/home/app/web/dev-poet-461212-d9-35a36f7ab681.json:ro
    ports:
      - "8127:8000"
    env_file:
      - ./.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  chromadb:
    container_name: nexora-chromadb
    image: chromadb/chroma:latest
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_ALLOW_RESET=true
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] 
    volumes:
      - chroma-data:/chroma/chroma
    restart: always

volumes:
  chroma-data:
    driver: local
